# Generated by Django 5.1.4 on 2025-01-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_divacetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAllInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=610, verbose_name='User Location')),
                ('come_from', models.CharField(max_length=610, verbose_name='User come from this web-site')),
                ('user_date', models.DateTimeField(auto_now_add=True, verbose_name='User come date')),
                ('device', models.CharField(max_length=610, verbose_name='Phone name')),
                ('browser', models.CharField(max_length=255, verbose_name='Browser')),
                ('browser_version', models.CharField(max_length=255, verbose_name='Browser version')),
                ('device_os', models.CharField(max_length=255, verbose_name='OS name')),
                ('ip_address', models.CharField(max_length=255, verbose_name='IP address')),
                ('os_version', models.CharField(max_length=255, verbose_name='OS_version')),
                ('is_pc', models.BooleanField(verbose_name='Is PC')),
                ('is_mobile', models.BooleanField(verbose_name='Is Mobile')),
                ('is_tablet', models.BooleanField(verbose_name='Is Tablet')),
            ],
        ),
    ]
