# Generated by Django 5.1.4 on 2025-01-02 20:36

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_userallinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininformations',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone number'),
        ),
    ]
